---
# Task file for role mesos-master

- name: Make sure the add-apt-repository command from the software-properties-common package is available
  apt: name=software-properties-common state=latest

- name: Make sure the GPG Key for Mesosphere is known to APT
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF state=present

- name: Make sure Oracle Java 8 Repository is in the list of repos
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Make sure Mesosphere APT Repository is in the list of repos
  apt_repository: repo='deb http://repos.mesosphere.com/ubuntu trusty main' state=present update_cache=yes

- name: Ensure auto-accept for the Oracle Java 8 license is set
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

- name: Ensure latest Oracle Java 8 is installed and set as system-wide default
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Make sure the mesosphere Package is installed
  apt: name=mesosphere state=present

- name: Ensure zookeeper id configured in /etc/zookeeper/conf/myid
  template: src=zookeeper/myid.j2 dest=/etc/zookeeper/conf/myid owner=root group=root mode="u=rw,g=r,o=r"
  notify: restart zookeeper

- name: Ensure config is correct in /etc/zookeeper/conf/zoo.cfg
  template: src=zookeeper/zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg owner=root group=root mode="u=rw,g=r,o=r"
  notify: restart zookeeper

- name: Ensure /usr/bin/zooinfo script is fixed (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=712778)
  template: src=zookeeper/zooinspector.j2 dest=/usr/bin/zooinspector owner=root group=root mode="u=rwx,g=rx,o=rx"
  notify: restart zookeeper

- name: Ensure /etc/mesos/zk file is configured properly
  template: src=mesos/zk.j2 dest=/etc/mesos/zk owner=root group=root mode="u=rwx,g=rx,o=rx"

- name: Ensure /etc/mesos-master/quorum file is configured properly
  template: src=mesos-master/quorum.j2 dest=/etc/mesos-master/quorum owner=root group=root mode="u=rwx,g=rx,o=rx"

- name: Ensure /etc/mesos-master/hostname file is configured properly
  template: src=mesos-master/hostname.j2 dest=/etc/mesos-master/hostname owner=root group=root mode="u=rwx,g=rx,o=rx"

- name: Ensure mesos-slave service is stopped and set to not run on booth
  service: name="mesos-slave" state=stopped enabled=no

- name: Make sure mesos-master service is brought up at the same time on all peers
  service: name="mesos-master" state=restarted enabled=yes

- name: Make sure marathon service is brought up at the same time on all peers
  service: name="marathon" state=restarted enabled=yes
