---
# Task file for role docker

- name: Make sure the GPG Key for Docker is known to APT
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: Make sure the Docker Repository is in the list of repos
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: Make sure the linux-extra package for our Kernel is installed to get access to the aufs driver
  apt: name=linux-image-extra-{{ansible_kernel}} state=present update_cache=yes

- name: Make sure Docker is installed
  apt: name=docker-engine state=present
